Adaptive menu
Nemhis/jira-analytics pull request #5
Opened 2023-01-10 15:37 UTC by DaTsvetkov21

add mobile menu

2023-01-11 10:28 UTC, Nemhis requested changes

2023-01-12 08:16 UTC, DaTsvetkov21 commented on src/components/AppHeader.vue
> +const isActiveDrawer = ref(false);
теперь `drawerIsActive`

2023-01-12 09:43 UTC, DaTsvetkov21 commented on src/components/AppHeader.vue
> +  .mobile {
изменил нейминг 
теперь все начинается c `header`

2023-01-12 09:55 UTC, DaTsvetkov21 commented on src/components/AppHeader.vue
> +@media screen and (min-width: 992px) {
сделал через `screen and (width >= 992px)`
соблюдал порядок начиная от мобильной версии и дальше

2023-01-12 10:33 UTC, Nemhis commented on src/components/AppHeader.vue
> +  .mobile {
Ну прям вот строчка, которая откомментирована не изменена, как и строчка с классом `desktop`. 
1 компонент = 1 БЭМ блок. Не может быть других блоков внутри файла стилей компонент. 
Также у тебя компонент называется `AppHeader`, а БЭМ блок называется `header`. Названия БЭМ блока и компонента лучше делать один, для удобства разработки (поиск блоков например)

2023-01-12 10:33 UTC, Nemhis commented on src/components/AppHeader.vue
> +@media screen and (min-width: 992px) {
Я не это имел ввиду. Дело в том, что `min-width` уже так работает. Твои стили должны выглядеть так:
```scss
// Переменный нужно вынести в отдельный файл, а цифры взяты рандомом
// это пример для понимания более целостной картины, в твоем случае цифры будут не совпадать, а переменных будет только две
$screen-sm: 400px;
$screen-md: 780px;
$screen-lg: 1024px;

.app-header {
  // TODO: стили мобильной версии
}

@media screen and (min-width: $screen-sm) {
  .app-header {
    // TODO: стили для экранов, у которых минимальная ширина не может быть меньше чем $screen-sm = 400px
  }
}

@media screen and (min-width: $screen-md) {
  .app-header {
    // TODO: стили для экранов, у которых минимальная ширина не может быть меньше чем $screen-md = 780px
  }
}

@media screen and (min-width: $screen-lg) {
  .app-header {
    // TODO: стили для экранов, у которых минимальная ширина не может быть меньше чем $screen-lg = 1024px
  }
}
```

2023-01-12 16:50 UTC, Nemhis requested changes

2023-01-12 16:50 UTC, Nemhis commented on src/components/AppHeader.vue
> +.app-header_mobile-menu {
элементы разделяются двумя подчеркиваниями

2023-01-12 16:50 UTC, Nemhis commented on src/components/AppHeader.vue
> +    visibility: hidden;
лучше `display: none`, так ты его из отображения совсем убираешь и браузер его не рендерит

2023-01-13 09:11 UTC, DaTsvetkov21 commented on src/components/AppHeader.vue
> +.app-header_mobile-menu {
проглядел. исправлено

2023-01-13 09:12 UTC, DaTsvetkov21 commented on src/components/AppHeader.vue
> +    visibility: hidden;
теперь `display: none`

2023-01-13 12:01 UTC, Nemhis requested changes

2023-01-13 12:01 UTC, Nemhis commented on src/components/AppHeader.vue
> +  z-index: 1000 !important;
слишком много `z-index` в файле, такое частое переопределение `z-index` приведет к багам, когда будет неожиданно элементы друг на друга налазить. Кажется что-то идет не так, если шапка конфликтует с дашбордом, то стоит только одной шапка задать `z-index`. Кажется у тебя недостаточно понимания работы `z-index` и наложения веркстки. Для чтения:
1. https://developer.mozilla.org/ru/docs/Web/CSS/z-index
2. https://habr.com/ru/post/431046/

2023-01-13 12:01 UTC, Nemhis commented on src/plugins/vuetify.ts
> +      md: 540,
За чем тебе столько разрешений, обнули все и оставь только те, с которыми ты работаешь в приложении

2023-01-13 12:05 UTC, DaTsvetkov21 commented on src/plugins/vuetify.ts
> +      md: 540,
по факту я тут ничего не юзаю вообще т.к. использую готовое решение `mdAndDown`

2023-01-13 12:06 UTC, DaTsvetkov21 commented on src/plugins/vuetify.ts
> +      md: 540,
Исправил

2023-01-13 14:09 UTC, DaTsvetkov21 commented on src/components/AppHeader.vue
> +  background-color: #eee !important;
подключил `sass` переменные и сделал через низ

2023-01-13 14:49 UTC, DaTsvetkov21 commented on src/components/AppHeader.vue
> +      <v-card v-if="drawerIsActive" class="app-header app-header__mobile-drawer">
Исправил

2023-01-13 14:49 UTC, DaTsvetkov21 commented on src/components/AppHeader.vue
> +  z-index: 1000 !important;
Исправил

2023-01-13 14:57 UTC, Nemhis commented on src/components/AppHeader.vue
> +      <v-card v-if="drawerIsActive" class="app-header">
не исправил, в разметке не должно быть два имени блока `app-header`

2023-01-13 14:57 UTC, Nemhis commented on src/components/AppHeader.vue
> +      <v-card v-if="drawerIsActive" class="app-header app-header__mobile-drawer">
не исправил, в разметке не должно быть два имени блока app-header

2023-01-13 14:59 UTC, Nemhis requested changes

2023-01-13 14:59 UTC, Nemhis commented on src/settings.scss
> +$app-bar-background: colors.$beige,
отступы сделай только, чтобы было понятно, что это вложенная конструкция

2023-01-13 15:00 UTC, DaTsvetkov21 commented on src/settings.scss
> +$app-bar-background: colors.$beige,
+

2023-01-14 12:52 UTC, Nemhis submitted a review, later dismissed

2023-01-14 12:55 UTC, Nemhis approved these changes

2023-01-14 12:55 UTC, merged