добавил фильтр
Nemhis/jira-analytics pull request #6
Opened 2023-01-22 16:29 UTC by DaTsvetkov21

- Добавил новые роуты на получение всех проектов\одного проекта
- добавил реактивность на загрузку тикетов при смене проекта
Не получилось добавить класс-адаптер для аватар урлов

2023-01-23 18:50 UTC, Nemhis requested changes

2023-01-23 18:50 UTC, Nemhis commented on src/adapters/Project.ts
> +    this.avatarUrls = String(raw['avatarUrls']['48x48']);
Не понял в чем проблема вызвать конструктор `AvatarUrls` здесь ?
`this.avatarUrls = AvatarUrls.fromRaw(raw['avatarUrls']);`
В шаблонах к урлу будешь обращаться как `project.avatarUrls.size24`

2023-01-23 18:50 UTC, Nemhis commented on src/api/modules/JiraApi.ts
> +  search(resourceId: string, projectKey: string): Promise<AxiosResponse> {
требуется более расширяемое решение. Если в фильтре будет 10 параметров, то у этой функции будет 11 аргументов ?

2023-01-23 18:50 UTC, Nemhis commented on src/api/modules/JiraApi.ts
> +  projects(resourceId: string): Promise<AxiosResponse> {
Методы должны называться глаголами, поэтому они олицетворяют действия.

2023-01-23 18:50 UTC, Nemhis commented on src/api/modules/JiraApi.ts
> +    return this.api.get<Project>(`/${resourceId}/rest/api/3/project/search`);
Зачем ты здесь пользуешься `genereic`ом ? для чего уточнение типа ?

2023-01-23 18:50 UTC, Nemhis commented on src/components/AppFilters.vue
> +.filter {
Название блока не совпадает с название компонента

2023-01-23 18:50 UTC, Nemhis commented on src/components/AppFilters.vue
> +<template>
Судя по названию компонента ты закладываешь, что в приложении не будет больше фильтров кроме фильтра по на странице DashBoard. Сейчас нет причин волноваться по этому поводу, но в дальнейшим если мы захотим сделать еще одну страницу со своим фильтров, то это компонент придется переименовывать. Также множественное число можно не использовать.

2023-01-23 18:50 UTC, Nemhis commented on src/components/AppFilters.vue
> +      <v-list-item v-bind="props" :prepend-avatar="item.raw.avatarUrls" @click="setQuery(item.raw.key)">
С инпутами так не работают: сейчас ты подвешиваешься на события клика и стирания, а должен использовать работу через пропс и событие и использовать `v-model`.
На самом деле `v-model` можно разложить на два атрибута
1. пропс - `:model-value`
2. событие - `@update:model-value`
Таким образом организуется двухсторонние связывание.
Вот прочти эту статью - https://learnvue.co/tutorials/v-model-guide

События с которыми ты работаешь сейчас используется именно для отловки кликов, аналитки, доплики взаимодействия с инпутами и т.д.

2023-01-23 18:50 UTC, Nemhis commented on src/components/AppFilters.vue
> +const setQuery = (key: string): void => {
Работу с роуетором лучше сразу вынести на верхний уровень приложения в родительский компонент, лучше концентрировать сложную логику работы типа взаимодействия с глобальным апи типа роутера внутри "умных" компонентов, в которых не избежать работы с роутером. А остальные компоненты оставлять "глупыми", чтобы их легко можно было протестировать.

2023-01-23 18:50 UTC, Nemhis commented on src/components/AppFilters.vue
> +const route = useRoute();
не используется

2023-01-28 00:46 UTC, DaTsvetkov21 commented on src/api/modules/JiraApi.ts
> +  projects(resourceId: string): Promise<AxiosResponse> {
исправил. теперь getProject\getProjects

2023-01-28 00:49 UTC, DaTsvetkov21 commented on src/api/modules/JiraApi.ts
> +    return this.api.get<Project>(`/${resourceId}/rest/api/3/project/search`);
не знаю на самом деле
удалил

2023-01-28 00:51 UTC, DaTsvetkov21 commented on src/components/AppFilters.vue
> +<template>
переименовал в FilterProject

2023-01-28 00:52 UTC, DaTsvetkov21 commented on src/components/AppFilters.vue
> +.filter {
переименовал в `.filter-project`

2023-01-28 05:49 UTC, DaTsvetkov21 commented on src/adapters/Project.ts
> +    this.avatarUrls = String(raw['avatarUrls']['48x48']);
Исправлено

2023-02-05 13:24 UTC, DaTsvetkov21 commented on src/api/modules/JiraApi.ts
> +  search(resourceId: string, projectKey: string): Promise<AxiosResponse> {
Исправлено

2023-02-05 13:24 UTC, DaTsvetkov21 commented on src/components/AppFilters.vue
> +      <v-list-item v-bind="props" :prepend-avatar="item.raw.avatarUrls" @click="setQuery(item.raw.key)">
Исправил

2023-02-05 13:24 UTC, DaTsvetkov21 commented on src/components/AppFilters.vue
> +const setQuery = (key: string): void => {
Исправил

2023-02-05 13:25 UTC, DaTsvetkov21 commented on src/components/AppFilters.vue
> +const route = useRoute();
не понял что именно
но вроде исправлено

2023-02-06 19:15 UTC, Nemhis commented on src/components/FilterProject.vue
> +<template>
Нейминг переводится как действие - `FilterProject` - фильтровать проект. Компоненты (элементы интерфейса) необходимо называть существительными. Правильнее с точки зрения английского языка писать `ProjectFilter`.  Вот тебе пример выражение `PocketBook` переводится как карманная книга, но если поменять слова местами - `bookPocket` то получается "Бронировать карман", что описывает действие и по смысля бред.

2023-02-06 19:15 UTC, Nemhis commented on src/components/FilterProject.vue
> +  filter: FilterProject;
Судя по названию сейчас компонент занимается фильтрацией только проектов, тогда зачем ему знать обо всем фильтре ? 
Я вижу две возможных реализации:
1. компонент отвечающий за фильтрацию проекта - занимается только работой с поиском по проектам и передачей его событием в родительский компонент. Тогда не логично давать знать данному компоненту о все фильтре. И тогда событие `submit` также странно выкидывать. Есть еще несколько плюсов, не буду расписывать, подумой сам)
2. переназвать компонент и считать его фильтром всей статистики. Тогда логично, чтобы фильтр знал о всем наборе допустимых значений для фильтрации и мог с ней работать.

2023-02-06 19:18 UTC, Nemhis requested changes

2023-02-06 19:18 UTC, Nemhis commented on src/views/Dashboard.vue
> +  router.push({ query: { ...filter } }).then(() => {
Так, а почему `fromRaw` не используется ? `{ query: { ...FilterProject.fromRaw(filter) }}`

2023-02-07 01:03 UTC, DaTsvetkov21 commented on src/views/Dashboard.vue
> +  router.push({ query: { ...filter } }).then(() => {
веротяно ты имел в виду toRaw. т.к. с fromRaw не работает стирание (в фильтр передаем нулл)
Исправил на to toRaw

2023-02-07 01:04 UTC, DaTsvetkov21 commented on src/adapters/FilterProject.ts
> +export default class FilterProject {
переименовал в Filter

2023-02-07 05:27 UTC, DaTsvetkov21 commented on src/components/FilterProject.vue
> +<template>
переименовал в ProjectFilter

2023-02-07 07:41 UTC, DaTsvetkov21 commented on src/store/jira.ts
> +    search(resourceId: string, params: Raw): Promise<Issue[]> {
Исправлено

2023-02-08 16:26 UTC, Nemhis requested changes

2023-02-08 16:26 UTC, Nemhis commented on src/adapters/Filter.ts
> +    return String(`project="${item?.projectId}"`);
Что будет сли проекта не будет ? например обнуления фильтра ? какой `jql` пошлется ?

2023-02-08 16:26 UTC, Nemhis commented on src/views/Dashboard.vue
> +      issues.value = [];
Зачем обнулять если нет проекта ?надо же заново загрузить все элементы. Их вполне можно загрузить вперемешку по всем проектам

2023-02-08 17:31 UTC, DaTsvetkov21 commented on src/adapters/Filter.ts
> +    return String(`project="${item?.projectId}"`);
по идее он не зашлется сюда т.к. я проверяю условие на наличие фильтра. если его нет, то запрос не выполняется. 
но я чуть изменил   ```
static toJQL(item: Filter): string {
    return item ? `project="${item?.projectId}"` : '';
  }
```

2023-02-08 17:51 UTC, DaTsvetkov21 commented on src/adapters/Filter.ts
> +    return String(`project="${item?.projectId}"`);
исправил

2023-02-08 17:51 UTC, DaTsvetkov21 commented on src/views/Dashboard.vue
> +      issues.value = [];
Исправил

2023-02-09 21:34 UTC, Nemhis requested changes

2023-02-09 21:34 UTC, Nemhis commented on src/views/Dashboard.vue
> +.issues-loading {
БЭМ нарушен

2023-02-09 21:34 UTC, Nemhis commented on src/components/AppFilter.vue
> +.filter-project {
БЭМ нарушен

2023-02-09 21:34 UTC, Nemhis commented on src/store/jira.ts
> +      if (params.projectId) {
Зачем проверять фильтр ? если не будет параметров для фильтрации, то `toJQL` вернет пустую строку. Ну вот и проверять результат трансорфации в `jql`

2023-02-09 21:34 UTC, Nemhis commented on src/views/Dashboard.vue
> +  issues.value = [];
Зачем обнулять ? если будет ошибка или что то не загрузится, то затрется прошлый стейт по непонятным причинам

2023-02-10 00:28 UTC, DaTsvetkov21 commented on src/views/Dashboard.vue
> +.issues-loading {
Исправил

2023-02-10 00:30 UTC, DaTsvetkov21 commented on src/views/Dashboard.vue
> +.issues-loading {
```
.dashboard {
  visibility: visible;
}
```

Добавил т.к. не могу оставить компонент пустым - ругается линтер, а ты говорил, что компонент должен быть )

2023-02-10 00:31 UTC, DaTsvetkov21 commented on src/components/AppFilter.vue
> +.filter-project {
исправил

2023-02-10 00:36 UTC, DaTsvetkov21 commented on src/views/Dashboard.vue
> +  issues.value = [];
Исправлено. Добавил `!isLoading` в условие показа дашборда

2023-02-10 00:43 UTC, DaTsvetkov21 commented on src/store/jira.ts
> +      if (params.projectId) {
Исправил

2023-02-10 07:13 UTC, Nemhis commented on src/views/Dashboard.vue
> +.issues-loading {
просто уберил класс из стилей, если нечего писать

2023-02-10 07:21 UTC, Nemhis requested changes

2023-02-10 07:21 UTC, Nemhis commented on src/components/AppFilter.vue
> +const isLoading: Ref<boolean> = ref(true);
По умолчанию лучше делать `false`.  При загрузке выставляешь в тру. Почему ? - если поменяется логика загрузки, то состояние останется не соответствующим. Правильно связанный код держать рядом, для прозрачности и т.д.

2023-02-10 07:26 UTC, DaTsvetkov21 commented on src/views/Dashboard.vue
> +.issues-loading {
убрал из стилей

2023-02-10 07:28 UTC, DaTsvetkov21 commented on src/components/AppFilter.vue
> +const isLoading: Ref<boolean> = ref(true);
Испарвил

2023-02-10 07:37 UTC, Nemhis approved these changes

2023-02-10 07:38 UTC, merged