Additional filters
Nemhis/jira-analytics pull request #7
Opened 2023-03-19 16:00 UTC by DaTsvetkov21

боль и страдания

2023-03-31 17:59 UTC, Nemhis requested changes

2023-03-31 17:59 UTC, Nemhis commented on src/adapters/JQLBuilder.ts
> +export default class JQLBuilder {
Данный класс нельзя назвать адаптером. Задача адаптера принимать данный с бекенда и производить безопасную трансформацию данных с апи в удобный формат для приложения. Данный класс имеет свою собственную логику и ответственность, а так как похожих сущностей в приложении нет, то данный класс можно положить прямо в `src/JQLBuilder`, в дальнейшем ему найдется более подходящее место, когда функционал будет расширяться.

2023-03-31 17:59 UTC, Nemhis commented on src/components/AppFilter.vue
> +      sprints.value = toArray(loadSprints['values']);
Тут кажется перемудрил немного. Должна быть такая цепочка вызовов:
1. Компонент запрашивает данные через стор
2. Стор запрашивает данный по апи
3. Апи делает запросы по сети

Каждый слой вызовов берет на себе определенную ответственность:
1. АПИ - определяет логику запроса по сети: метод, маршрут
2. стор - принимает ответ от апи и подготоваливает данный для использования в приложении
3. компонент - отображает данные и отвечает за взаимодействие с пользователем

Какие я вижу на данный момент проблемы:
1. На данный момент стор не обрабатывае данный от апи, а передает их напрямую в компонент. Зачем тогда адаптер и стор, можно напрямую вызывать апи.
2. Често говоря я не понимаю, что в этой строчке происходит, промис в `then` принимает в себя массив спринтов, причем переменная называет глаголом, как будто это действие, далее вызывается свойство, которое не задекларировано нигде - `values`, хакерным способом для сброса типизации. Надо этот момент привести в порядок

2023-03-31 17:59 UTC, Nemhis commented on src/components/AppFilter.vue
> +      isLoading.value = true;
В данном кейсе загрузка уже закончена, состоянии не отразит реальность в лучшем случаем, в худшем пользователь во время загрузки что-то введет и после загрузки у него сбросятся данные в инпуте

2023-03-31 17:59 UTC, Nemhis commented on src/components/AppFilter.vue
> +      error.value = response ? (response.data as Raw) : null;
Опять же потеря типизации, правильно для ошибок создать адаптер , описать их свойства и принимать здесь их

2023-03-31 17:59 UTC, Nemhis commented on src/components/AppFilter.vue
> +      issues.value = loadedIssues;
+1 к состоянию загрузки

2023-03-31 17:59 UTC, Nemhis commented on src/components/AppFilter.vue
> +      isLoading.value = true;
+1 к состоянию загрузки

2023-03-31 17:59 UTC, Nemhis commented on src/adapters/Board.ts
> +  values: BoardField = {
Странное свойство, почему у доски есть `values` ? давай сместим `id` и `name` на корневой уровень компонента, чтобы можно было обращаться как `board.id` и `board.name`. Плюс дефолтные значения проще сбросить, так как они не имеют смысла, все равно в конструкторе происходит инициализация данных свойств.

2023-03-31 17:59 UTC, Nemhis commented on src/components/AppFilter.vue
> +  if (id === draftFilter.implementerIds) {
Почему массив сравнивает с числом ? если `id` это всегда массив, то стоит отобразить это в названии - `ids`

2023-03-31 17:59 UTC, Nemhis commented on src/components/AppFilter.vue
> +  getUsers('');
Передача пустой строки выглядит костыльно и не очевидно при вызове, если не передавать ничего на апи, то жира не отдаст пользователей ? если да, то убери этот костыль внутрь стора, чтобы работа приложении в компонентах выглядела более логично

2023-03-31 17:59 UTC, Nemhis commented on src/components/AppFilter.vue
> +  if (id === draftFilter.issueIds) {
+1 про `id`

2023-05-07 18:28 UTC, merged

2023-05-18 15:27 UTC, DaTsvetkov21 commented on src/adapters/JQLBuilder.ts
> +export default class JQLBuilder {
fix

2023-05-18 15:30 UTC, DaTsvetkov21 commented on src/api/modules/JiraApi.ts
> +    return this.api.get(`/${resourceId}/rest/agile/1.0/board?${projectId ? `projectKeyOrId=${projectId}` : ''}`);
fix

2023-05-18 15:39 UTC, DaTsvetkov21 commented on src/components/AppFilter.vue
> +  if (id === draftFilter.implementerIds) {
fix